# Generated by Django 5.2 on 2025-11-05 06:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kyc_api_gateway", "0007_clientmanagement_password_clientmanagement_two_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginFailAttempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("agent_browser", models.TextField(blank=True, null=True)),
                ("client_details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "auth_client_login_fail_attempts",
            },
        ),
        migrations.CreateModel(
            name="AccountUnlockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("self", "Self Unlock"), ("admin", "Admin Unlock")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("success", models.BooleanField(default=False)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_unlock_performed",
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
                (
                    "unlocked_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_unlock_received",
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
            options={
                "db_table": "auth_client_account_unlock_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uniqid", models.CharField(db_index=True, max_length=100)),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=255)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
            options={
                "db_table": "client_api_log",
            },
        ),
        migrations.CreateModel(
            name="ForgotPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
            options={
                "db_table": "auth_client_forgot_password",
            },
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=1024, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("login_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "agent_browser",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("request_headers", models.JSONField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
            options={
                "db_table": "auth_client_login_session",
                "ordering": ["-login_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("action", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("successful", models.BooleanField(default=False)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
            options={
                "db_table": "auth_client_password_reset_log",
            },
        ),
    ]
