# Generated by Django 5.2 on 2025-11-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0001_initial"),
        ("kyc_api_gateway", "0007_clientmanagement_password_clientmanagement_two_step"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ForgotPassword",
            new_name="ForgotPasswordOtp",
        ),
        migrations.RenameModel(
            old_name="LoginFailAttempts",
            new_name="LoginFailAttempt",
        ),
        migrations.AlterModelTable(
            name="forgotpasswordotp",
            table="auth_client_forgot_password_otp",
        ),
        migrations.AlterModelTable(
            name="loginfailattempt",
            table="auth_client_login_fail_attempt",
        ),
    ]
