# Generated by Django 5.2 on 2025-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0002_rename_forgotpassword_forgotpasswordotp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountunlocklog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
