# Generated by Django 5.2 on 2025-11-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0003_alter_accountunlocklog_timestamp"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="apilog",
            table="auth_client_api_log",
        ),
    ]
