# Generated by Django 5.2.5 on 2025-11-06 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0004_alter_apilog_table"),
        ("kyc_api_gateway", "0008_clientmanagement_login_attempts_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ForgotPasswordOtp",
            new_name="ForgotPassword",
        ),
        migrations.RemoveField(
            model_name="loginfailattempt",
            name="email",
        ),
        migrations.AddField(
            model_name="loginfailattempt",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="forgotpassword",
            table="auth_client_forgot_password",
        ),
        migrations.CreateModel(
            name="ChangePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("new_password_hash", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("success", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_changed_by",
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_password_logs",
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Password Log",
                "verbose_name_plural": "Client Change Password Logs",
                "db_table": "auth_client_change_password_log",
            },
        ),
    ]
