# Generated by Django 5.2.5 on 2025-11-06 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0005_rename_forgotpasswordotp_forgotpassword_and_more"),
        ("kyc_api_gateway", "0008_clientmanagement_login_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginOtpVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("request_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Delivered"),
                            (3, "Failed"),
                            (4, "Verified"),
                            (5, "Expired"),
                            (6, "Cancelled"),
                        ]
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
            options={
                "db_table": "auth_client_login_otp_verification",
            },
        ),
    ]
