# Generated by Django 5.2.5 on 2025-11-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0006_loginotpverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile_number", models.CharField(max_length=15)),
                ("message", models.TextField()),
                ("sms_type", models.IntegerField(choices=[(1, "Client Login OTP")])),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Delivered"),
                            (3, "Failed"),
                            (4, "Verified"),
                            (5, "Expired"),
                            (6, "Cancelled"),
                        ],
                        default=1,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "auth_system_sms_log",
            },
        ),
    ]
