# Generated by Django 5.2.5 on 2025-11-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0007_smslog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="smslog",
            table="auth_client_sms_log",
        ),
    ]
