# Generated by Django 5.2.5 on 2025-11-07 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0008_alter_smslog_table"),
        ("kyc_api_gateway", "0009_clientmanagement_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[("access", "Access"), ("refresh", "Refresh")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to="kyc_api_gateway.clientmanagement",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ChangePassword",
        ),
    ]
