# Generated by Django 5.2.5 on 2025-11-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_auth", "0009_blacklistedtoken_delete_changepassword"),
        ("kyc_api_gateway", "0009_clientmanagement_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blacklistedtoken",
            old_name="created_at",
            new_name="blacklisted_at",
        ),
        migrations.AlterField(
            model_name="blacklistedtoken",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kyc_api_gateway.clientmanagement",
            ),
        ),
        migrations.AlterModelTable(
            name="blacklistedtoken",
            table="client_auth_blacklistedtoken",
        ),
    ]
