# Generated by Django 5.2 on 2025-11-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0010_rename_created_at_blacklistedtoken_blacklisted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginsession',
            old_name='expiry_at',
            new_name='access_expiry_at',
        ),
        migrations.AddField(
            model_name='loginsession',
            name='refresh_expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
