# Generated by Django 5.2.5 on 2025-10-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0004_rename_vendor_namee_vendormanagement_vendor_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kycclientservicesmanagement",
            options={},
        ),
        migrations.RemoveField(
            model_name="kycclientservicesmanagement",
            name="priority",
        ),
    ]
