# Generated by Django 5.2.5 on 2025-10-29 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0005_alter_kycclientservicesmanagement_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UatPassportDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "file_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("surname", models.CharField(blank=True, max_length=255, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("date_of_issue", models.DateField(blank=True, null=True)),
                ("date_of_application", models.DateField(blank=True, null=True)),
                (
                    "application_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status_text", models.TextField(blank=True, null=True)),
                ("vendor", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uat_passport_details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UatPassportRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "file_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("vendor", models.CharField(blank=True, max_length=100, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fail", "Fail")],
                        max_length=10,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "passport_verification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passport_logs",
                        to="kyc_api_gateway.uatpassportdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uat_passport_verification_request_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
