# Generated by Django 5.2 on 2025-11-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0006_uatpassportdetails_uatpassportrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uatdrivinglicenserequestlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uatdrivinglicenserequestlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
