# Generated by Django 5.2 on 2025-11-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0006_uatpassportdetails_uatpassportrequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmanagement",
            name="password",
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name="clientmanagement",
            name="two_step",
            field=models.BooleanField(default=False),
        ),
    ]
