# Generated by Django 5.2.5 on 2025-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0007_clientmanagement_password_clientmanagement_two_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmanagement",
            name="login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clientmanagement",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
