# Generated by Django 5.2.5 on 2025-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0007_alter_uatrcdetails_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uatrcdetails",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="response_metadata",
            new_name="full_response",
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="masked_name",
            new_name="less_info",
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="national_permit_issued_by",
            new_name="variant",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="fit_upto",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="non_use_from",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="non_use_status",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="non_use_to",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="permit_issue_date",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="permit_valid_from",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="tax_paid_upto",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="vendor",
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="fit_up_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="rto_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="body_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="cubic_capacity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="insurance_upto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="latest_by",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="manufacturing_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="manufacturing_date_formatted",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="national_permit_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="national_permit_upto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="no_cylinders",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="owner_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="permit_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="permit_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="permit_valid_upto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="pucc_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="pucc_upto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="rc_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="seat_capacity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="sleeper_capacity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="standing_capacity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="tax_upto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="unladen_weight",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_chasi_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_engine_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_gross_weight",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="wheelbase",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
