# Generated by Django 5.2.5 on 2025-11-03 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0008_alter_uatrcdetails_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uatrcdetails",
            options={},
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="full_response",
            new_name="challan_details",
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="variant",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="less_info",
            new_name="masked_name",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="fit_up_to",
        ),
        migrations.RemoveField(
            model_name="uatrcdetails",
            name="rto_code",
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="fit_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="national_permit_issued_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="non_use_from",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="non_use_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="non_use_to",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="permit_issue_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="permit_valid_from",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="response_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="tax_paid_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="vendor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="body_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="cubic_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="insurance_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="latest_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="manufacturing_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="manufacturing_date_formatted",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="national_permit_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="national_permit_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="no_cylinders",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="owner_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="permit_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="permit_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="permit_valid_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="pucc_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="pucc_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="rc_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="registration_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="seat_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="sleeper_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="standing_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="tax_upto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="unladen_weight",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_chasi_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_engine_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_gross_weight",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="wheelbase",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
