# Generated by Django 5.2.5 on 2025-11-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0008_clientmanagement_login_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmanagement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientmanagement",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
