# Generated by Django 5.2.5 on 2025-11-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0009_alter_uatrcdetails_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uatrcdetails",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="challan_details",
            new_name="blacklist_info",
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="fit_upto",
            new_name="fit_up_to",
        ),
        migrations.RenameField(
            model_name="uatrcdetails",
            old_name="vendor",
            new_name="fitness_upto",
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="case_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="deleted_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="less_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="manufactured_month_year",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="profile_match",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="puc_expiry_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="rto_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="state_cd",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="status_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="updated_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="variant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uatrcdetails",
            name="vehicle_class_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="blacklist_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="financed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="latest_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="masked_name",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="national_permit_issued_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="non_use_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="rc_number",
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="seat_capacity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="sleeper_capacity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="standing_capacity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="uatrcdetails",
            name="vehicle_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
