# Generated by Django 5.2.5 on 2025-11-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0011_uataddressmatch_uataddressmatchrequestlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uataddressmatchrequestlog",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uataddressmatchrequestlog",
            name="address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
