# Generated by Django 5.2.5 on 2025-11-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0012_alter_uataddressmatchrequestlog_address1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uataddressmatch",
            name="vendor_name",
        ),
        migrations.RemoveField(
            model_name="uataddressmatchrequestlog",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="uataddressmatchrequestlog",
            name="request_id",
        ),
    ]
