# Generated by Django 5.2.5 on 2025-11-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0013_remove_uataddressmatch_vendor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uataddressmatch",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uataddressmatch",
            name="address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
