# Generated by Django 5.2.5 on 2025-11-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0014_uataddressmatch_address1_uataddressmatch_address2"),
    ]

    operations = [
        migrations.AddField(
            model_name="uatbillrequestlog",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatdrivinglicenserequestlog",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatnamematchrequestlog",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatpanrequestlog",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatpassportrequestlog",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatrcrequestlog",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uatvoterrequestlog",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
