# Generated by Django 5.2.5 on 2025-11-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0015_uatbillrequestlog_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uatpassportdetails",
            old_name="dob",
            new_name="dobd",
        ),
        migrations.RenameField(
            model_name="uatpassportrequestlog",
            old_name="status_code",
            new_name="status_codee",
        ),
    ]
