# Generated by Django 5.2.5 on 2025-11-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0016_rename_dob_uatpassportdetails_dobd_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uatpassportdetails",
            old_name="dobd",
            new_name="dob",
        ),
        migrations.RenameField(
            model_name="uatpassportrequestlog",
            old_name="status_codee",
            new_name="status_code",
        ),
    ]
