# Generated by Django 5.2.5 on 2025-11-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0017_rename_dobd_uatpassportdetails_dob_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="uatpassportrequestlog",
            table="uat_passport_log",
        ),
    ]
