# Generated by Django 5.2.5 on 2025-11-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0018_alter_uatpassportrequestlog_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uatpassportdetails",
            name="vendor",
        ),
    ]
