# Generated by Django 5.2.5 on 2025-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0019_remove_uatpassportdetails_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uatpassportdetails",
            name="created_by",
        ),
        migrations.AddField(
            model_name="uatpassportdetails",
            name="deleted_by",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
