# Generated by Django 5.2 on 2025-11-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_api_gateway', '0007_uatdrivinglicenserequestlog_ip_address_and_more'),
        ('kyc_api_gateway', '0009_clientmanagement_is_active_and_more'),
        ('kyc_api_gateway', '0020_remove_uatpassportdetails_created_by_and_more'),
    ]

    operations = [
    ]
