# Generated by Django 5.2.5 on 2025-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0021_merge_20251107_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycclientservicesmanagement",
            name="uat_api_limit",
            field=models.IntegerField(default=100),
        ),
    ]
