# Generated by Django 5.2.5 on 2025-11-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc_api_gateway", "0022_kycclientservicesmanagement_uat_api_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycmyservices",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
